### PR TITLE
Sos/fix typo

### PR DESCRIPTION
**Pull request by sarahscott**

### CODE REVIEW

**Comment by okwme** [comment]
lol am i supposed to merge this?

**Comment by sarahscott** [comment]
nooo was a mistake! it's meant for https://github.com/scammer-market/scammer-contracts, which is a fork of folia so it automatically made a PR against u

**Comment by sarahscott** [comment]
entschuldingung!

**Comment by okwme** [comment]
lolol
<3 <3 <3
excited to see scammer!!

**Pull request closed without merging**
